# Generated by Django 6.0.1 on 2026-01-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Название')),
                ('description_short', models.CharField(max_length=300, verbose_name='Короткое описание')),
                ('description_long', models.TextField(verbose_name='Описание')),
                ('lng', models.DecimalField(decimal_places=14, max_digits=18, verbose_name='Долгота')),
                ('lat', models.DecimalField(decimal_places=14, max_digits=18, verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ('title',),
            },
        ),
    ]
