# Generated by Django 6.0.1 on 2026-01-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placeimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ('order',), 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
