# Generated by Django 6.0.1 on 2026-01-11 17:39

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_placeimage_options_alter_placeimage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
    ]
