# Generated by Django 6.0.1 on 2026-01-13 00:12

from django.db import migrations, models


def add_short_description(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    for place in Place.objects.all():
        place.short_description = place.description_short
        place.save()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_description_long'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.AddField(
            model_name='place',
            name='short_description',
            field=models.TextField(default='', verbose_name='Короткое описание'),
            preserve_default=False,
        ),

        migrations.RunPython(
            add_short_description,
        ),

        migrations.RemoveField(
            model_name='place',
            name='description_short',
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядковый номер'),
        ),
    ]
